In [1]:
import torch

In [2]:
tensor = torch.tensor([1,2,3,4,5])
print(tensor.shape)
s = torch.sum(tensor,dim=0)
print(s, s.shape) # scalar has no shape

torch.Size([5])
tensor(15) torch.Size([])


In [3]:
tensor = torch.tensor(
    [
        [1,2,3], [4,5,6]
    ]
    ) # 2x3
print(tensor.shape)
print("Dimension 0")
dimo0 = torch.sum(tensor, dim=0) # adds both lists (1 + 4, 2 + 5, 3 + 6)
print(dimo0)
print()
print("Dimension 1")
dimo1 = torch.sum(tensor, dim=1) # adds inner list (1+2+3, 4+5+6)
print(dimo1)

print()
print("Inner most (just like last access in list)")
dims = torch.sum(tensor, dim=-1)
print(dims)



torch.Size([2, 3])
Dimension 0
tensor([5, 7, 9])

Dimension 1
tensor([ 6, 15])

Inner most (just like last access in list)
tensor([ 6, 15])


In [ ]:
# 3d!!
tensor = torch.tensor([
    [ [1,2,3], [4,5,6] ],
    [ [7,8,9], [10,11,12] ]
])
print(tensor.shape) # 2 outer dimensions, each has 2 elements

torch.Size([2, 2, 3])
